### ISSUE TITLE
Charge profile limiting not working if current is set (tested with the simulator)

### ISSUE THREAD

**Issue by rpseng** [matth-x/MicroOcpp#310] opened 2024-05-29 13:31 UTC
Hello,

I was playing with charge profiles and found out that if a charging profile is set with current as the limit (as opposed to power), the simulator will be limited at zero power.

It looks like the source of the problem is the following line:
https://github.com/matth-x/MicroOcpp/blob/e879c0e6988d7946959ce8cf18e05c4b623d21ba/src/MicroOcpp.cpp#L628

Where even if a current is set as limit it will use the power limit (-1) in that case.

Thank you in advance.

**Comment by matth-x** [comment] 2024-06-05 18:05
Hi @rpseng,

Thanks for pointing that out! It's a regression bug and I was totally unaware of it because I only used power-based charging schedules recently.

-1 means that no limit is defined by Smart Charging. This is missing in the API doc which I also fixed now.

**Closed by matth-x** 2024-06-05 18:05 UTC
